package ClassAssignments.Day37ClassAssignment_11thMay;
//Find kth character.First row is 0 .Each next row is generated by replacing all 0>0,1 and 1->1,0.
//Given N and k , find the kth character
public class KthCharacter {
    public static void main(String[] args) {
       int n=5;
       int k=10;
        int result=findKcharac(n,k);
        System.out.println(result);

    }

    private static int findKcharac(int n,int k){
        if(n==1)return 0;
        int par=findKcharac(n-1,k/2);
        if(k%2==0){
            return par;
        }else{
            return 1-par;
        }
    }
}
